FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install uv
RUN uv pip install --system --no-cache-dir -r requirements.txt

COPY . .

CMD sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${SERVICE_PORT:-8000}"
